#pragma once

// Veiled Experts (idk bro) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x4)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// AnimBlueprintGeneratedClass DefaultPlayer.DefaultPlayer_C
// 0xE080 (0xE630 - 0x05B0)
class UDefaultPlayer_C : public UPDPlayerAnimInstance
{
public:
	struct FPointerToUberGraphFrame                    UberGraphFrame;                                           // 0x05B0(0x0008) (ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_15;                                    // 0x05B8(0x0048)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_14;                        // 0x0600(0x01C8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_14;                                    // 0x07C8(0x0048)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_54;                         // 0x0810(0x00B0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_12;                         // 0x08C0(0x00A0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_53;                         // 0x0960(0x00B0)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_13;                        // 0x0A10(0x01C8)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_12;                        // 0x0BD8(0x01C8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_32;                          // 0x0DA0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_62;                           // 0x0E58(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_61;                           // 0x0E80(0x0028)
	struct FAnimNode_Root                              AnimGraphNode_Root_7;                                     // 0x0EA8(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_51;                        // 0x0ED8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_50;                        // 0x0F00(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_31;                          // 0x0F28(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_52;                         // 0x0FA0(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_30;                          // 0x1050(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_26;                             // 0x10C8(0x0030)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_51;                         // 0x10F8(0x00B0)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_13;                                    // 0x11A8(0x0048)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_12;                                    // 0x11F0(0x0048)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_29;                          // 0x1238(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_50;                         // 0x12B0(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_35;                        // 0x1360(0x00E0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_28;                          // 0x1440(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_49;                         // 0x14B8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_34;                        // 0x1568(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_25;                             // 0x1648(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_8;                             // 0x1678(0x00B0)
	struct FAnimNode_Root                              AnimGraphNode_Root_6;                                     // 0x1728(0x0030)
	struct FAnimNode_LinkedInputPose                   AnimGraphNode_LinkedInputPose_3;                          // 0x1758(0x0078)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_5;                            // 0x17D0(0x00C8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_33;                        // 0x1898(0x00E0)
	struct FAnimNode_Root                              AnimGraphNode_Root_5;                                     // 0x1978(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_49;                        // 0x19A8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_48;                        // 0x19D0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_47;                        // 0x19F8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_46;                        // 0x1A20(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_45;                        // 0x1A48(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_44;                        // 0x1A70(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_43;                        // 0x1A98(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_42;                        // 0x1AC0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_41;                        // 0x1AE8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_40;                        // 0x1B10(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_48;                         // 0x1B38(0x00B0)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_11;                        // 0x1BE8(0x01C8)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_10;                        // 0x1DB0(0x01C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_60;                           // 0x1F78(0x0028)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_2;                              // 0x1FA0(0x00C8)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_4;                            // 0x2068(0x00C8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_32;                        // 0x2130(0x00E0)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer_6;                       // 0x2210(0x02B8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_24;                             // 0x24C8(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_59;                           // 0x24F8(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_47;                         // 0x2520(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_27;                          // 0x25D0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_26;                          // 0x2648(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_25;                          // 0x26C0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_24;                          // 0x2738(0x0078)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_12;                        // 0x27B0(0x00C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_23;                             // 0x2878(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_58;                           // 0x28A8(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_22;                             // 0x28D0(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_57;                           // 0x2900(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_11;                        // 0x2928(0x00C8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_11;                                    // 0x29F0(0x0048)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_56;                           // 0x2A38(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_21;                             // 0x2A60(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_7;                             // 0x2A90(0x00B0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_39;                        // 0x2B40(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_38;                        // 0x2B68(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_46;                         // 0x2B90(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_23;                          // 0x2C40(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_22;                          // 0x2CB8(0x0078)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_20;                             // 0x2D30(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_55;                           // 0x2D60(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_19;                             // 0x2D88(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_6;                             // 0x2DB8(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_31;                          // 0x2E68(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_30;                          // 0x2F20(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_29;                          // 0x2FD8(0x00B8)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_37;                        // 0x3090(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_36;                        // 0x30B8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_35;                        // 0x30E0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_34;                        // 0x3108(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_33;                        // 0x3130(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_32;                        // 0x3158(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_31;                        // 0x3180(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_30;                        // 0x31A8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_29;                        // 0x31D0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_28;                        // 0x31F8(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_54;                           // 0x3220(0x0028)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend;                                // 0x3248(0x00C8)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_3;                            // 0x3310(0x00C8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_31;                        // 0x33D8(0x00E0)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer_5;                       // 0x34B8(0x02B8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_18;                             // 0x3770(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_53;                           // 0x37A0(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_45;                         // 0x37C8(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_21;                          // 0x3878(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_20;                          // 0x38F0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_19;                          // 0x3968(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_18;                          // 0x39E0(0x0078)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_10;                        // 0x3A58(0x00C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_17;                             // 0x3B20(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_52;                           // 0x3B50(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_16;                             // 0x3B78(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_51;                           // 0x3BA8(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_50;                           // 0x3BD0(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_9;                         // 0x3BF8(0x00C8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_10;                                    // 0x3CC0(0x0048)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_15;                             // 0x3D08(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_5;                             // 0x3D38(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_28;                          // 0x3DE8(0x00B8)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_27;                        // 0x3EA0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_26;                        // 0x3EC8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_25;                        // 0x3EF0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_24;                        // 0x3F18(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_23;                        // 0x3F40(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_22;                        // 0x3F68(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_21;                        // 0x3F90(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_20;                        // 0x3FB8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_19;                        // 0x3FE0(0x0028)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_9;                         // 0x4008(0x01C8)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_8;                         // 0x41D0(0x01C8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_44;                         // 0x4398(0x00B0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_14;                             // 0x4448(0x0030)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_7;                         // 0x4478(0x01C8)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_6;                         // 0x4640(0x01C8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_43;                         // 0x4808(0x00B0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_13;                             // 0x48B8(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_49;                           // 0x48E8(0x0028)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_5;                              // 0x4910(0x0058)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_12;                             // 0x4968(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_48;                           // 0x4998(0x0028)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_4;                              // 0x49C0(0x0058)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_11;                             // 0x4A18(0x0030)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_10;                             // 0x4A48(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_4;                             // 0x4A78(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_27;                          // 0x4B28(0x00B8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_42;                         // 0x4BE0(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_30;                        // 0x4C90(0x00E0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_2;                            // 0x4D70(0x00C8)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer_4;                       // 0x4E38(0x02B8)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer_3;                       // 0x50F0(0x02B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_26;                          // 0x53A8(0x00B8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_29;                        // 0x5460(0x00E0)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive;                              // 0x5540(0x00C8)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer_2;                       // 0x5608(0x02B8)
	struct FAnimNode_PDBlendSpacePlayer                AnimGraphNode_PDBlendSpacePlayer;                         // 0x58C0(0x02B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_25;                          // 0x5B78(0x00B8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_11;                         // 0x5C30(0x00A0)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_5;                         // 0x5CD0(0x01C8)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_4;                         // 0x5E98(0x01C8)
	struct FAnimNode_Root                              AnimGraphNode_Root_4;                                     // 0x6060(0x0030)
	struct FAnimNode_LinkedInputPose                   AnimGraphNode_LinkedInputPose_2;                          // 0x6090(0x0078)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_4;                   // 0x6108(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_47;                           // 0x61D8(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_41;                         // 0x6200(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_40;                         // 0x62B0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_39;                         // 0x6360(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_24;                          // 0x6410(0x00B8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_38;                         // 0x64C8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_28;                        // 0x6578(0x00E0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_23;                          // 0x6658(0x00B8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_27;                        // 0x6710(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_26;                        // 0x67F0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_25;                        // 0x68D0(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_37;                         // 0x69B0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_36;                         // 0x6A60(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_35;                         // 0x6B10(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_24;                        // 0x6BC0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_23;                        // 0x6CA0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_22;                        // 0x6D80(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_21;                        // 0x6E60(0x00E0)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_3;                   // 0x6F40(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_46;                           // 0x7010(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_34;                         // 0x7038(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_20;                        // 0x70E8(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_19;                        // 0x71C8(0x00E0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_22;                          // 0x72A8(0x00B8)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_5;                               // 0x7360(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_4;                               // 0x7468(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_3;                               // 0x7570(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_2;                               // 0x7678(0x0108)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_4;                    // 0x7780(0x0020)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_4;                    // 0x77A0(0x0020)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_33;                         // 0x77C0(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_45;                           // 0x7870(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_44;                           // 0x7898(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_32;                         // 0x78C0(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_31;                         // 0x7970(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_43;                           // 0x7A20(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_30;                         // 0x7A48(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_18;                        // 0x7AF8(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_17;                        // 0x7BD8(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_16;                        // 0x7CB8(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_29;                         // 0x7D98(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_15;                        // 0x7E48(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_28;                         // 0x7F28(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_14;                        // 0x7FD8(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_27;                         // 0x80B8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_13;                        // 0x8168(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_12;                        // 0x8248(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_26;                         // 0x8328(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_11;                        // 0x83D8(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_25;                         // 0x84B8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_10;                        // 0x8568(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_24;                         // 0x8648(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_9;                         // 0x86F8(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_23;                         // 0x87D8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_8;                         // 0x8888(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_7;                         // 0x8968(0x00E0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_10;                         // 0x8A48(0x00A0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_6;                         // 0x8AE8(0x00E0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_22;                         // 0x8BC8(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_5;                         // 0x8C78(0x00E0)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone;                                 // 0x8D58(0x0108)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_3;                    // 0x8E60(0x0020)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_3;                    // 0x8E80(0x0020)
	struct FAnimNode_Root                              AnimGraphNode_Root_3;                                     // 0x8EA0(0x0030)
	struct FAnimNode_LinkedInputPose                   AnimGraphNode_LinkedInputPose;                            // 0x8ED0(0x0078)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_21;                          // 0x8F48(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_42;                           // 0x9000(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_8;                         // 0x9028(0x00C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_41;                           // 0x90F0(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_17;                          // 0x9118(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_16;                          // 0x9190(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_21;                         // 0x9208(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_15;                          // 0x92B8(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_14;                          // 0x9330(0x0078)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_20;                          // 0x93A8(0x00B8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_20;                         // 0x9460(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_40;                           // 0x9510(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_19;                         // 0x9538(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_18;                         // 0x95E8(0x00B0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_7;                         // 0x9698(0x00C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_39;                           // 0x9760(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_17;                         // 0x9788(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_19;                          // 0x9838(0x00B8)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_13;                          // 0x98F0(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_16;                         // 0x9968(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_15;                         // 0x9A18(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_38;                           // 0x9AC8(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_37;                           // 0x9AF0(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_14;                         // 0x9B18(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_13;                         // 0x9BC8(0x00B0)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_2;                   // 0x9C78(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_36;                           // 0x9D48(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_12;                         // 0x9D70(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_18;                          // 0x9E20(0x00B8)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_11;                         // 0x9ED8(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_10;                         // 0x9F88(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_9;                          // 0xA038(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_8;                          // 0xA0E8(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_7;                          // 0xA198(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_35;                           // 0xA248(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_12;                          // 0xA270(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_11;                          // 0xA2E8(0x0078)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_17;                          // 0xA360(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_34;                           // 0xA418(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_33;                           // 0xA440(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_10;                          // 0xA468(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_9;                           // 0xA4E0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_8;                           // 0xA558(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_7;                           // 0xA5D0(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_6;                           // 0xA648(0x0078)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_5;                           // 0xA6C0(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_6;                          // 0xA738(0x00B0)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_5;                          // 0xA7E8(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_32;                           // 0xA898(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive;                     // 0xA8C0(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_31;                           // 0xA990(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_4;                           // 0xA9B8(0x0078)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_4;                          // 0xAA30(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_30;                           // 0xAAE0(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_3;                          // 0xAB08(0x00B0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_3;                           // 0xABB8(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_9;                          // 0xAC30(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_29;                           // 0xACD0(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_2;                           // 0xACF8(0x0078)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_8;                          // 0xAD70(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_28;                           // 0xAE10(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_27;                           // 0xAE38(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_7;                          // 0xAE60(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer;                             // 0xAF00(0x0078)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_3;                              // 0xAF78(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_2;                              // 0xAFD0(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve;                                // 0xB028(0x0058)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_9;                                     // 0xB080(0x0048)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_6;                         // 0xB0C8(0x00C8)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_5;                         // 0xB190(0x00C8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_8;                                     // 0xB258(0x0048)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_16;                          // 0xB2A0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_26;                           // 0xB358(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_25;                           // 0xB380(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_24;                           // 0xB3A8(0x0028)
	struct FAnimNode_Root                              AnimGraphNode_Root_2;                                     // 0xB3D0(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_18;                        // 0xB400(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_17;                        // 0xB428(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_16;                        // 0xB450(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_15;                        // 0xB478(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_14;                        // 0xB4A0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_13;                        // 0xB4C8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_12;                        // 0xB4F0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_11;                        // 0xB518(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_10;                        // 0xB540(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_2;                          // 0xB568(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_4;                         // 0xB618(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_3;                         // 0xB6F8(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_9;                              // 0xB7D8(0x0030)
	struct FAnimNode_LinkedAnimLayer                   AnimGraphNode_LinkedAnimLayer_5;                          // 0xB808(0x00B0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_8;                              // 0xB8B8(0x0030)
	struct FAnimNode_RefPose                           AnimGraphNode_LocalRefPose;                               // 0xB8E8(0x0018)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_7;                              // 0xB900(0x0030)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum;                            // 0xB930(0x00B0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_2;                         // 0xB9E0(0x00E0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer;                           // 0xBAC0(0x00E0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_6;                              // 0xBBA0(0x0030)
	struct FAnimNode_LinkedAnimLayer                   AnimGraphNode_LinkedAnimLayer_4;                          // 0xBBD0(0x00B0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_5;                              // 0xBC80(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_9;                         // 0xBCB0(0x0028)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_3;                             // 0xBCD8(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_15;                          // 0xBD88(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_14;                          // 0xBE40(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_13;                          // 0xBEF8(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_12;                          // 0xBFB0(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_11;                          // 0xC068(0x00B8)
	struct FAnimNode_LinkedAnimGraph                   AnimGraphNode_SubInstance_2;                              // 0xC120(0x00A0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_23;                           // 0xC1C0(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_10;                          // 0xC1E8(0x00B8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_7;                                     // 0xC2A0(0x0048)
	bool                                               __CustomProperty_bAimingIdleState_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC2E8(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0xC2E9(0x0003) MISSED OFFSET
	float                                              __CustomProperty_AimInterpTime_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC2EC(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               __CustomProperty_MirrorFinalPose_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC2F0(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x7];                                       // 0xC2F1(0x0007) MISSED OFFSET
	struct FPDPerSpecificWeaponAnimDatas               __CustomProperty_PSpecificWeaponAnimDatas_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC2F8(0x00E0)
	bool                                               __CustomProperty_SWStanceIsValid_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC3D8(0x0001) (ZeroConstructor, IsPlainOldData)
	bool                                               __CustomProperty_WStanceIsValid_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC3D9(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x6];                                       // 0xC3DA(0x0006) MISSED OFFSET
	struct FPDPWUsingInABPAnimDatas                    __CustomProperty_PWAnimDatas_3C7ADD0C48259AE1DF84B89D5192CD5B;// 0xC3E0(0x0128) (ZeroConstructor, IsPlainOldData)
	struct FAnimNode_LinkedAnimGraph                   AnimGraphNode_SubInstance;                                // 0xC508(0x00A0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_4;                         // 0xC5A8(0x00C8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_9;                           // 0xC670(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_22;                           // 0xC728(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_21;                           // 0xC750(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_20;                           // 0xC778(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_19;                           // 0xC7A0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_18;                           // 0xC7C8(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_6;                                     // 0xC7F0(0x0048)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_3;                         // 0xC838(0x00C8)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_6;                          // 0xC900(0x00A0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_4;                              // 0xC9A0(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_2;                             // 0xC9D0(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_17;                           // 0xCA80(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_8;                           // 0xCAA8(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_16;                           // 0xCB60(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_5;                                     // 0xCB88(0x0048)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_15;                           // 0xCBD0(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_2;                         // 0xCBF8(0x00C8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_7;                           // 0xCCC0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_14;                           // 0xCD78(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_6;                           // 0xCDA0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_13;                           // 0xCE58(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_4;                                     // 0xCE80(0x0048)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_12;                           // 0xCEC8(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_5;                          // 0xCEF0(0x00A0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend;                           // 0xCF90(0x00C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_11;                           // 0xD058(0x0028)
	struct FAnimNode_LinkedAnimLayer                   AnimGraphNode_LinkedAnimLayer_3;                          // 0xD080(0x00B0)
	struct FAnimNode_LinkedAnimLayer                   AnimGraphNode_LinkedAnimLayer_2;                          // 0xD130(0x00B0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_10;                           // 0xD1E0(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_4;                          // 0xD208(0x00A0)
	struct FAnimNode_LinkedAnimLayer                   AnimGraphNode_LinkedAnimLayer;                            // 0xD2A8(0x00B0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_8;                         // 0xD358(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_7;                         // 0xD380(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_6;                         // 0xD3A8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_5;                         // 0xD3D0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_4;                         // 0xD3F8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_3;                         // 0xD420(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_2;                         // 0xD448(0x0028)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_3;                         // 0xD470(0x01C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_3;                              // 0xD638(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult;                           // 0xD668(0x0028)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer_2;                         // 0xD690(0x01C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_2;                              // 0xD858(0x0030)
	struct FAnimNode_PDSequencePlayer                  AnimGraphNode_PDSequencePlayer;                           // 0xD888(0x01C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult;                                // 0xDA50(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine;                               // 0xDA80(0x00B0)
	struct FAnimNode_Root                              AnimGraphNode_Root;                                       // 0xDB30(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_9;                            // 0xDB60(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_3;                          // 0xDB88(0x00A0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_5;                           // 0xDC28(0x00B8)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_2;                    // 0xDCE0(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_2;                    // 0xDD00(0x0020)
	struct FAnimNode_CopyBone                          AnimGraphNode_CopyBone_2;                                 // 0xDD20(0x00F0)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace;                      // 0xDE10(0x0020)
	struct FAnimNode_CopyBone                          AnimGraphNode_CopyBone;                                   // 0xDE30(0x00F0)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace;                      // 0xDF20(0x0020)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_3;                                     // 0xDF40(0x0048)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_4;                           // 0xDF88(0x00B8)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_2;                                     // 0xE040(0x0048)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_8;                            // 0xE088(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_3;                           // 0xE0B0(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_7;                            // 0xE168(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_6;                            // 0xE190(0x0028)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_2;                          // 0xE1B8(0x00A0)
	struct FAnimNode_Mirror                            AnimGraphNode_Mirror;                                     // 0xE258(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_2;                           // 0xE280(0x00B8)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose;                             // 0xE338(0x00B8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_5;                            // 0xE3F0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_4;                            // 0xE418(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_3;                            // 0xE440(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_2;                            // 0xE468(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose;                              // 0xE490(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot;                                       // 0xE4B8(0x0048)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool;                            // 0xE500(0x00A0)
	struct FAnimNode_PoseSnapshot                      AnimGraphNode_PoseSnapshot;                               // 0xE5A0(0x0090)

	static UClass* StaticClass()
	{
		static UClass* ptr = NULL;
		if(!ptr)
			ptr = UObject::FindClass("AnimBlueprintGeneratedClass DefaultPlayer.DefaultPlayer_C");
		
		return ptr;
	}


	void Facial(struct FPoseLink* Facial);
	void GroggyLocomotion(struct FPoseLink* GroggyLocomotion);
	void FireRecoil(const struct FPoseLink& InPose_FireRecoil, struct FPoseLink* FireRecoil);
	void DefaultLocomotion(struct FPoseLink* DefaultLocomotion);
	void AimOffset(const struct FPoseLink& InPose_AimOffset, struct FPoseLink* AimOffset);
	void Upper(const struct FPoseLink& InPose_Upper, struct FPoseLink* Upper);
	void AnimGraph(struct FPoseLink* AnimGraph);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_0C1A33AC42A2D9EF29452DBB8B37CAF1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_2956D13D41DB8EDE492C2FA61CC4783B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_C7B2D4804C565FA187A9418113FFE505();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_10CD0D5640FEB5EB5A4B9E8DFDE3E8A7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_300EA4C24787C932F904D4900B40AABC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_6183CE754B35AC9FBC9D82AC5FFB3BB4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_91990AE8424C460EDE193F8797563DCF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_14267E7B47B5048CED43D29794CC257B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_1E38A4864A7A7F93B21BD08A6052EED5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_BFF6E34241B7C826F15333A9B15348BF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_21D993F14B874D5020A2CA9C2E3E01B9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_E2B8E1D34339ED9CFD8E79946EF17ED2();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_D3AEA0224BF3AEBE670FEFBCB9F4F10E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_0789DAF14E2A79D2D1A04A923A624015();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_4B37FC8A4441BD4A7B61058785F56FA6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_3AE4DAE84914BE0AF389AA9F91BC6033();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_663B24364D92825EC9BCFF8A12B5A443();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_5C4B1862451D9CAE2220129E68672802();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_F1DBF97B4CC5E74D5E14628B39598781();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendListByBool_A2E779484F7BBBD8A56D7585F68B1DE9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_PDSequencePlayer_21C1D96F42BCC62B31966BBDB470C346();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_PDSequencePlayer_F67016F348CBFBCE2BE1F7B99E289D3E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendListByBool_8121C9C94EE0D1F1AF02259E99501A7F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_ModifyBone_317D507C4BCE7ECEF352AD8C062FA29B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_LinkedAnimGraph_3C7ADD0C48259AE1DF84B89D5192CD5B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_3F53A9C34553E87F7737D4A5D8E99D30();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_0548762B4829B6CD8B5D76B5136D66CB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_30ECAA6840500D75BB70E18219251C68();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_1CC571C646CE943DC00A6797DC103658();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_AC736CEE4F3404337D12BDBC973219B0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_EB24ED11423776DF9E100CA4E450FE42();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendListByBool_9889121A49FDCCBC485719B0268E4972();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_E4DB08664EE6DAF95E2C4EBFF5C2DAE8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendListByBool_23346DAC473745B69AB7E4AA60A45DDA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendListByBool_ED3B310B4C6570E9E81EF8ADC03EA1FF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_8C6992664E552C27AE6B80924C07CEC7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_A1A4CAF545FCD0BDF629F2B1C6B08757();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_E4C8B49A4EA495854153D6B85FACF4FC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_8E677FB9469221198B52C59837656A45();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_BlendSpacePlayer_AD1DFB944ECC9BE05946EF83605102B0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_681DD81C49F5AD04204160AF0104B7F3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_E902D6A141F7EFEF54F7FAB2E9C9465A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_519134E841B7A1B3E9B5E285F3DF8CB7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_CD89F8914AE607EBCF8FF69B30E03704();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_FFC0E995423394DEDC2A9686C05F6114();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_7B19E8C249720A7A0C184DAF9539AB6F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_D916AA1A4E89C34075D5D591F01C064A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_D9FFE21C4194EE51EF7424A143144C84();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayer_AnimGraphNode_TransitionResult_40EFEE1948E12950CEACEC88EE6B2882();
	void ExecuteUbergraph_DefaultPlayer(int EntryPoint);
};


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
